### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by jinzezhi** [piaolin/DetectDee#1]
![image](https://user-images.githubusercontent.com/93123422/236366086-f08167a4-1807-4da3-99d2-614fc4eb178b.png)

**Comment by piaolin** [comment]
TimeOnly layout是**Go 1.20**的新特性，请使用Go 1.20或以上版本或重新拉取。

建议直接使用[已编译版本](https://github.com/piaolin/DetectDee/releases/)。
