### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by andre-santos1** [piaolin/DetectDee#12]
I've installed it from github and I am able to run "go run  ."

But after that any command I try yields a "command not found error". 

See screenshot bellow.

![2023-05-10 08_48_15-Lorna Cole  Running  - Oracle VM VirtualBox](https://github.com/piaolin/DetectDee/assets/53203402/6ab95161-d85d-406b-aa12-278a4314e5df)

**Comment by piaolin** [comment]
If you download the source code to run, you can run it in two ways:
1. run directly
```shell
go run . -h
go run . detect -h
go run . detect -n theUsernameYouWantDetect
```
3. run after build
```shell
go build .
./DetectDee detect -h
./DetectDee detect -n theUsernameYouWantDetect
```
