### ISSUE TITLE
Do not search anything

### ISSUE THREAD

**Issue by fagner521** [piaolin/DetectDee#14]
The instalation has made in a windows machine, i have downloaded the source code and compiled with go using wsl not work too, so i go away and try the .exe binary and nothing happen.

Installation image:

![image](https://github.com/piaolin/DetectDee/assets/29678604/2f972c5f-8a76-4feb-90d6-a781948c1c99)

Error image:

![image](https://github.com/piaolin/DetectDee/assets/29678604/ff77fa2e-d6d1-4b29-b4b1-7ff5f5b5aaba)

**Comment by piaolin** [comment]
At present, email and phone number search are only backup search methods for username search, with not much website data. More data will be gradually added later.
