### ISSUE TITLE
Dont search by email and phone

### ISSUE THREAD

**Issue by Bars7878** [piaolin/DetectDee#19]
Hi!
I try search by email and phone number but no results recieved. Windows and Linux has a same results. Result.txt is empty, no error messages. By username (-n) works.
Please, What could be the problem?

**Comment by elliwinehouse** [comment]
yes, i support you. i faced the same problem. dear developer, please fix this bug.

**Comment by muralidharanramanujam** [comment]
Hi Team,
How can we view the result.txt file after the execution of command in command prompt! Any one Kindly help!

**Comment by piaolin** [comment]
At present, email and phone number search are only backup search methods for username search, with not much website data. More data will be gradually added later.
