### ISSUE TITLE
Result.Txt is not open

### ISSUE THREAD

**Issue by muralidharanramanujam** [piaolin/DetectDee#20]
Hi Team,

After Execution of Command, That prompt shows save to result.txt file. But I can't able to view that file. How Can we search the file. Need Your Support!

**Comment by muralidharanramanujam** [comment]
![Capture](https://github.com/piaolin/DetectDee/assets/18161679/83626a53-cc5a-4f5c-b9bd-a6cc2573e73e)

And Also Can't able to Perform Screenshot Functionality. Herewith im enclosed the Snap Kindly look into that

**Comment by piaolin** [comment]
At present, email and phone number search are only backup search methods for username search, with not much website data. More data will be gradually added later.
