### ISSUE TITLE
Gets stuck and sto[s as xsssql. Doesn't go on to rest of list. 

### ISSUE THREAD

**Issue by hughsheehy** [piaolin/DetectDee#3]
xsssql         : http://www.xsssql.com/article/author/hughsheehy requests error, retry 3/3

**Comment by piaolin** [comment]
This is not an stuck, but a information to tell you that after repeated request three times, the requests has failed.

All requests are multithreaded and will not block unless you specify a delay in the site data(data.json)

**Comment by hughsheehy** [comment]
That's fine, but it also doesn't go on to the rest of the networks listed on the documentation. It stops there.
