### ISSUE TITLE
Email search doesn't work

### ISSUE THREAD

**Issue by qurbat** [piaolin/DetectDee#4]
I can see that email search simply queries the same URLs that are queried for usernmes but replaces the part of the URL with an email address. This is ineffective and does not generate any results on any of the sites supported by the program. I suggest, for the time being, until proper email support is added, that the 'search by email' mention in the project's `README.md` file (along with 'search by phone') is removed.

**Comment by piaolin** [comment]
The search by email or phone is being refined.
