### ISSUE TITLE
Not able to search by phone number of email address

### ISSUE THREAD

**Issue by polkahon** [piaolin/DetectDee#7]
I'm using the latest linux release. When I ran using -p or -e according to the examples provided, it does not detect the input parameter.

./DetectDee detect -p 15822575984,13188524682
INFO   [2023-05-07 05:43:19] Detect for []    

./DetectDee detect -e mail@gmail.com,test@163.com
INFO   [2023-05-07 05:43:10] Detect for []

**Comment by piaolin** [comment]
At present, email and phone number search are only backup search methods for username search, with not much website data. More data will be gradually added later.
