### ISSUE TITLE
Small bug on the email search 

### ISSUE THREAD

**Issue by jaunenathan** [piaolin/DetectDee#8]
Hello, I have a little problem with the e-mail search function. Basically, the program understands that I want to search for an e-mail but does not take the address that I have indicated on the terminal    

![image](https://user-images.githubusercontent.com/38536450/236674841-bdd035bf-d514-4576-af08-2279784efbd4.png)

**Comment by jaunenathan** [comment]
I just saw in the other Issues that this feature was under development but I find it a bit stupid to announce it on the repo if the feature does not work yet ...

**Comment by piaolin** [comment]
Sorry, I will finish the data collection as soon as possible.
