### ISSUE TITLE
邮箱和手机号查找无法使用

### ISSUE THREAD

**Issue by flaray** [piaolin/DetectDee#9]
PS D:\Sec\DetectDee_windows_amd64> ./DetectDee detect -p 15822575984,13188524682
INFO   [2023-05-10 11:31:05] Detect for []
PS D:\Sec\DetectDee_windows_amd64> ./DetectDee detect -e mail1111@gmail.com,test1111@163.com
INFO   [2023-05-10 11:31:35] Detect for []

**Comment by moonD4rk** [comment]
这块儿 log 打的有点模糊，加上 `-g` flag 搜索 Google 结果的时候会有查找结果。

**Comment by piaolin** [comment]
并不是没有生效，而是目前email和phone只是作为username的备用查询手段，没有太多数据，后期会添加email和phone的数据。
